### ISSUE TITLE
Remove unnecessary extra reader

### ISSUE THREAD

**Issue by BoogieMonster1O1** [acmpesuecc/pinger#18]
https://github.com/acmpesuecc/pinger/blob/eac1c46f3e68392b3489a95c66a2449404c2802b/src/main/java/pinger/Pinger.java#L14
This reader is not necessary as there is already another created. Nor is the reader closed. It should be removed and all occurrences of `reader1` should be changed to `reader`

**Comment by sreechand2002** [comment]
i would like to work on it
