### ISSUE TITLE
Handle exceptions instead of declaring them to be thrown

### ISSUE THREAD

**Issue by BoogieMonster1O1** [acmpesuecc/pinger#2]
The line https://github.com/acmpesuecc/pinger/blob/master/src/main/java/pinger/Pinger.java#L11 declares that an `IOException` is thrown by the method. 

Instead of declaring it to be thrown, the entire method's contents should be wrapped in a `try {...} catch(...) {...}` statement to allow custom handling of the exception. The exception's stack trace should be printed along with some meaningful information about the exception.

**Comment by sreechand2002** [comment]
i would like to work on it
