### ISSUE TITLE
Append a new line after reading each line from the reader

### ISSUE THREAD

**Issue by BoogieMonster1O1** [acmpesuecc/pinger#5]
After reading each line from the reader, a new line (`\n`) should be added to the string builder make the content easier to read. 
Specifically right after line 40. 
https://github.com/acmpesuecc/pinger/blob/8b164118db9035a5bd6fe8775164dbcfefa546e0/src/main/java/pinger/Pinger.java#L35-L41

**Comment by sreechand2002** [comment]
i would like to work on it
