### ISSUE TITLE
Perform an instanceof check before casting

### ISSUE THREAD

**Issue by BoogieMonster1O1** [acmpesuecc/pinger#7]
https://github.com/acmpesuecc/pinger/blob/8b164118db9035a5bd6fe8775164dbcfefa546e0/src/main/java/pinger/Pinger.java#L16
Although this cast is usually safe, it is best to wrap it with an `instanceof` check inside an `if` statement to ensure that it is actually an `HttpURLConnection`. An exception should be thrown in the `else` block to indicate that it was not an `HttpURLConnection`.

**Comment by sreechand2002** [comment]
i would like to work on it

**Comment by Rishabkashyap14** [comment]
!bounty 100

**Comment by Rishabkashyap14** [comment]
!bounty 0
